### ISSUE TITLE
CLMUL-SIMD implementation of GF2To16

### ISSUE THREAD

**Issue by drskalman** [drskalman/reed-solomon-erasure#1]
The following steps take us to a proper implementation which is hopefully faster.
   - [ ] only use clmulqdq to replace polynomial multiplication. #2
   - [ ] implement fast reduction. #3
   - [ ] implement 2 simultanous mulitplications using 64bit registers. #4
   - [ ] SIMD-ify mul_slice and mul_slice_add using previous step and perhaps "faster crate".

**Comment by drskalman** [comment]
multipication and fast reduction implemented, now focusing on 2 simultanous multiplications.
